package com.axcel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainForm {
    private JPanel mainPanel;
    private JLabel result;
    private JButton OKButton;
    private JTextField input;
    private JButton eraseButton;
    private JTextField nameInput;
    private JTextField dateOgBirthInput;
    private JLabel titel;
    private JLabel nameLable;
    private JLabel dobLable;


    public MainForm() {
        OKButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {


                result.setText(input.getText());
            }
        });

        eraseButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                result.setText("                 . ");
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("MainForm");
        frame.setContentPane(new MainForm().mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public void setData(MainFormData data) {
        nameInput.setText(data.getName());
        dateOgBirthInput.setText(data.getDateOfBrith());
        input.setText(data.getFormInput());
    }

    public void getData(MainFormData data) {
        data.setName(nameInput.getText());
        data.setDateOfBrith(dateOgBirthInput.getText());
        data.setFormInput(input.getText());
    }

    public boolean isModified(MainFormData data) {
        if (nameInput.getText() != null ? !nameInput.getText().equals(data.getName()) : data.getName() != null)
            return true;
        if (dateOgBirthInput.getText() != null ? !dateOgBirthInput.getText().equals(data.getDateOfBrith()) : data.getDateOfBrith() != null)
            return true;
        if (input.getText() != null ? !input.getText().equals(data.getFormInput()) : data.getFormInput() != null)
            return true;
        return false;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setBackground(new Color(-2693140));
        nameInput = new JTextField();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(nameInput, gbc);
        dateOgBirthInput = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(dateOgBirthInput, gbc);
        nameLable = new JLabel();
        nameLable.setText("Name:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        mainPanel.add(nameLable, gbc);
        dobLable = new JLabel();
        dobLable.setText("Date of Birth");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        mainPanel.add(dobLable, gbc);
        input = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(input, gbc);
        result = new JLabel();
        result.setText("This is my 1st GUI");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        mainPanel.add(result, gbc);
        eraseButton = new JButton();
        eraseButton.setText("Erase");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        mainPanel.add(eraseButton, gbc);
        titel = new JLabel();
        titel.setText("JAVA GUI Test");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        mainPanel.add(titel, gbc);
        OKButton = new JButton();
        OKButton.setText("OK");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        mainPanel.add(OKButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
